// src/frontend/components/cards/TimelineCard.vue
<script setup>
const props = defineProps({
    startDate: {
        type: String,
    },
    endDate: {
        type: String,
    },
    iconSrc: {
        type:String,
    },
    desc: {
        type: String
    }

})
</script>

<template>
    <div class="timeline-card">
        <div class="timeline-timespan">{{startDate}} - {{endDate}}</div>
        <div class="timeline-icon">
            <div class="timeline-dot"></div>
            <img :src="iconSrc" alt="D-Soft">
        </div>
        <div class="timeline-desc">
            <slot></slot>
        </div>
    </div>
</template>

<style scoped>
.timeline-card {
    display: grid;
    grid-template-columns: repeat(24, 1fr);
    font-family: sans-serif;
    line-height: 1.4;
}
.timeline-timespan {
    grid-column: span 2;
    font-size: 0.8rem;
    text-align: right;
    padding-right: 5px;
    color: #bbb;
}
.timeline-icon {
    grid-column: span 3;
    vertical-align: top;
    border-left: 2px solid #cfcfcf;
    position: relative;
    padding-bottom: 1rem;
    margin-left: 6px;
}
.timeline-dot {
    position: absolute;
    top: 0px;
    left: -7px;
    width: 8px;
    height: 8px;
    border-radius: 7px;
    background-color: #cfcfcf;
    border: 2px solid white;
}
.timeline-icon img {    
    border-radius: 5px;
    width: 100%;
    /* max-width: 100px; */
    margin-left: 10px;
    /* background-color: #fff; */
}
.timeline-desc {
    grid-column: span 19;
    vertical-align: top;
    font-size: 1rem;
    padding-left: 20px;
    padding-bottom: 20px;
    text-align: justify;
}

@media (max-width: 600px) {
    .timeline-icon {
        grid-column: span 6;
    }
    .timeline-desc {
        grid-column: span 16;
    }
    .timeline-timespan {
        font-size: 0.6rem;
    }
}

@media (max-width: 700px) {
    .timeline-icon {
        grid-column: span 5;
    }
    .timeline-desc {
        grid-column: span 17;
    }
}
</style>

// src/components/HomepageTimelines/timeline-card.tsx
import React from "react";
import clsx from "clsx";

import styles from "./timeline-card.module.css";

interface Props {
  startDate: string;
  endDate: string;
  iconSrc: string;
  desc: string;
}

const TimelineCard = ({ startDate, endDate, iconSrc, desc }: Props) => {
  return (
    <div className="flex">
      <div className="relative border-solid border-0 border-r-[1px]">
        <div className="w-[100px] md:w-[150px] pr-3">
          <img
            src={iconSrc}
            className={
              "w-[100%] rounded dark:border-white dark:border-[1px] " +
              (iconSrc.endsWith("svg")
                ? "bg-gray-800 px-1 py-2 dark:border-solid"
                : "")
            }
          />
        </div>
        <span className="absolute top-[3px] right-[-7px] h-[13px] w-[13px] bg-white dark:bg-black  rounded-full border-solid border-2"></span>
      </div>
      <div className="pl-3">
        <div className="text-sm">
          {startDate}-{endDate}
        </div>
        <div className="w-full pb-4 text-justify">{desc}</div>
      </div>
    </div>
  );
};

export default TimelineCard;
